### ISSUE TITLE
Not an issue: Trying to Connect Lambda NodeJS code to Mongo/Dynamo DB

### ISSUE THREAD

**Issue by motwaniumesh** [alexa/skill-sample-nodejs-team-lookup#14]
Hi,

Could you please guide me to get data from Mongo/Dynamo DB instead of hardcoding it in Lambda Node JS file. The data is given in array format right now in Lamda Node JS file. I need to connect to database and bring the details.

Request you to kindly help and let me know.

Regards,
Umesh

**Comment by kraunak** [comment]
@motwaniumesh You can connect to db from Lambda using connectors and configure connection string in ENV Var.

**Comment by motwaniumesh** [comment]
Hi,

Could you please give me an example. I am new to database and need some
guidance if you can provide.

Regards
Umesh

**Comment by kraunak** [comment]
You can use [Mongoose](http://mongoosejs.com) for MongoDB to connect and query or any other connector based on your Database.

Inside your handler helper 

```
// Import Deps
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

// Create a Model with your schema / Table 
const Model = mongoose.model('Model', { <ModelSchema> });

// Query you DB
Model.find().then((result) => {
// Do what ever you want.
});
```

**Comment by motwaniumesh** [comment]
Thanks a lot. I will try as you guided

**Comment by kraunak** [comment]
Let me know if you need any other assistance.

Raunak

On 19-Apr-2018, at 8:49 AM, motwaniumesh <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks a lot. I will try as you guided

**Comment by motwaniumesh** [comment]
Sure... I will try it and let you know. Thank you once again.

**Comment by motwaniumesh** [comment]
Hi Raunak,

I am facing a new issue where i am doing authentication. I have put in a
new issue

Any kind of help is much appreciated.

Regards
Umesh

**Comment by kraunak** [comment]
@motwaniumesh unfortunately I don't hold experience with ASK OAuth but surely will try to help. Other off topic suggestion _Post your issues in correct/relevant repo so you will be getting better support._ Don't take this otherwise 😄 and feel free to tag me if you need any help.  Also close this issue if you get this working. 👍

**Comment by motwaniumesh** [comment]
I am so sorry. But yes thanks for making me understand :)

**Comment by franklin-lobb** [comment]
Looks to be resolved.  If not, please open a new issue.
