### ISSUE TITLE
OAuth "state" parameter too long, can it be shortened?

### ISSUE THREAD

**Issue by motwaniumesh** [alexa/skill-sample-nodejs-team-lookup#17]
I am referring to below link where the issue is discussed
https://forums.developer.amazon.com/questions/75718/oauth-state-parameter-too-long-can-it-be-shortened.html?page=1&pageSize=10&sort=votes

anybody has solution to this issue? any alternative approach that I can follow?

I want it to be less than 600 characters

**Comment by kraunak** [comment]
@motwaniumesh After reading the above thread I got so far that we can't control state JWT length. AWS dev can only help you to get this below 600. 

[Amazon Developer Forums](https://forums.developer.amazon.com) will be the right place to ask for help on this.

**Comment by motwaniumesh** [comment]
Thank you :)

**Comment by franklin-lobb** [comment]
Looks to be resolved.  If not, please open a new issue.
