### ISSUE TITLE
alexa-skill-kit-sdk-factskill is not available

### ISSUE THREAD

**Issue by chuckf201** [alexa/skill-sample-nodejs-team-lookup#22]
2-Lambda-function.md:
step5:
There are two boxes labeled "Author from scratch" and "Blueprints". Click the radio button in the box titled "Blueprints" then choose the blueprint named "alexa-skill-kit-sdk-factskill". We have created a blueprint as a shortcut to getting everything set up for your skill. You can search for a blueprint using the provided search box. This blueprint adds the alexa-sdk to your Lambda function so that you don't have to upload it yourself.
"alexa-skill-kit-sdk-factskill" is not in "Blueprint".
Where is it?

**Comment by chuckf201** [comment]
found it in serverless

**Comment by RyanQ96** [comment]
Hi, I found the same problem and I checked serverless, still no one has sdk, could you please share more info?

**Comment by bghanchi** [comment]
I have also face the same problem

**Comment by bghanchi** [comment]
Please help?

**Comment by lksstr** [comment]
May we have free aws account thats why its not available there for us

**Comment by subaharan** [comment]
I am facing same issue. alexa-skill-kit-sdk-factskill  not available. any solution found
