### ISSUE TITLE
Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by caffeinePlease** [alexa/skill-sample-nodejs-team-lookup#9]
After a good amount of time learning how to use command line and ASK CLI, I've successfully cloned the skill, uploaded to the dev console and AWS. Testing, I've opened the skill, but none of the other intents work. Having not changed a line of code, I'm not sure what's producing this.

![snip_20180311155813](https://user-images.githubusercontent.com/36041420/37257856-0ce33a90-2545-11e8-9d44-75e9c0e65dd5.png)

**Comment by azayarni** [comment]
Seems the example was not really tested. Strict mode does not allow conditions without brackets. You have to fix the code on your own.

line 233 exchange

```
        if (canSearch) 
            let searchQuery = slots[canSearch].value;
```
        
with

```
        if (canSearch) {
            let searchQuery = slots[canSearch].value;
        }
```

There is another typo bug. I will open an issue.

**Comment by caffeinePlease** [comment]
Please let me know what else needs tidying up—I’m desperate to get this skill working (after customizing, of course). Any more tips would be appreciated…

**Comment by azayarni** [comment]
Additionally, you have to change misspelled 'respone' to 'response' in the index.js file. That's it.

**Comment by JennJin** [comment]
Closing issue. Fixed by latest Merge. #12
